org: jviry
app: diary-app  # Choose your app name
service: diary-app

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node20
    platform: node
    format: esm
    banner:
      js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);"
    external:
      - serverless-http
      - '@prisma/client'
      - bcrypt

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    SPOTIFY_CLIENT_ID: ${env:SPOTIFY_CLIENT_ID}
    SPOTIFY_CLIENT_SECRET: ${env:SPOTIFY_CLIENT_SECRET}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}


package:
  individually: true
  patterns:
    - src/generated/prisma/**
    - '!src/generated/prisma/query-engine-*'
    - src/generated/prisma/query-engine-rhel-*
    - node_modules/bcrypt/**

functions:
  auth:
    handler: src/handlers/auth.handler
    events:
      - httpApi:
          path: /auth/{proxy+}
          method: ANY

  letters:
    handler: src/handlers/letters.handler
    events:
      - httpApi:
          path: /letters/{proxy+}
          method: ANY

  pings:
    handler: src/handlers/pings.handler
    events:
      - httpApi:
          path: /pings/{proxy+}
          method: ANY
